nutritional_info = [{'user_input': '0.5 cup cooked moong dal',
  'food_name': 'moong dal',
  'serving_qty': 0.5,
  'serving_unit': 'cup',
  'serving_weight_grams': 103.23,
  'nf_calories': 117.83,
  'nf_total_fat': 1.02,
  'nf_saturated_fat': 0.1,
  'nf_total_carbohydrate': 20.26,
  'nf_dietary_fiber': 7.95,
  'nf_sugars': 2.9,
  'nf_protein': 7.85},
 {'user_input': '0.5 cup uncooked quinoa',
  'food_name': 'uncooked quinoa',
  'serving_qty': 0.5,
  'serving_unit': 'cup',
  'serving_weight_grams': 85,
  'nf_calories': 312.8,
  'nf_total_fat': 5.16,
  'nf_saturated_fat': 0.6,
  'nf_total_carbohydrate': 54.54,
  'nf_dietary_fiber': 5.95,
  'nf_sugars': None,
  'nf_protein': 12},
 {'user_input': '1 cup small-chopped cauliflower',
  'food_name': 'cauliflower',
  'serving_qty': 1,
  'serving_unit': 'cup',
  'serving_weight_grams': 124,
  'nf_calories': 28.52,
  'nf_total_fat': 0.56,
  'nf_saturated_fat': 0.09,
  'nf_total_carbohydrate': 5.1,
  'nf_dietary_fiber': 2.85,
  'nf_sugars': 2.58,
  'nf_protein': 2.28},
 {'user_input': '0.5 cup green peas',
  'food_name': 'green peas',
  'serving_qty': 0.5,
  'serving_unit': 'cup',
  'serving_weight_grams': 80,
  'nf_calories': 67.2,
  'nf_total_fat': 0.18,
  'nf_saturated_fat': 0.03,
  'nf_total_carbohydrate': 12.5,
  'nf_dietary_fiber': 4.4,
  'nf_sugars': 4.74,
  'nf_protein': 4.29},
 {'user_input': '2 teaspoons grated fresh ginger',
  'food_name': 'fresh ginger',
  'serving_qty': 2,
  'serving_unit': 'teaspoons',
  'serving_weight_grams': 4.56,
  'nf_calories': 3.64,
  'nf_total_fat': 0.03,
  'nf_saturated_fat': 0.01,
  'nf_total_carbohydrate': 0.81,
  'nf_dietary_fiber': 0.09,
  'nf_sugars': 0.08,
  'nf_protein': 0.08},
 {'user_input': '1 teaspoon ground coriander',
  'food_name': 'ground coriander',
  'serving_qty': 1,
  'serving_unit': 'teaspoon',
  'serving_weight_grams': 1.73,
  'nf_calories': 5.17,
  'nf_total_fat': 0.31,
  'nf_saturated_fat': 0.02,
  'nf_total_carbohydrate': 0.95,
  'nf_dietary_fiber': 0.73,
  'nf_sugars': None,
  'nf_protein': 0.21},
 {'user_input': '0.5 teaspoon ground cumin',
  'food_name': 'ground cumin',
  'serving_qty': 0.5,
  'serving_unit': 'teaspoon',
  'serving_weight_grams': 1.03,
  'nf_calories': 3.84,
  'nf_total_fat': 0.23,
  'nf_saturated_fat': 0.02,
  'nf_total_carbohydrate': 0.45,
  'nf_dietary_fiber': 0.11,
  'nf_sugars': 0.02,
  'nf_protein': 0.18},
 {'user_input': '0.5 teaspoon ground turmeric',
  'food_name': 'ground turmeric',
  'serving_qty': 0.5,
  'serving_unit': 'teaspoon',
  'serving_weight_grams': 1.53,
  'nf_calories': 4.78,
  'nf_total_fat': 0.05,
  'nf_saturated_fat': 0.03,
  'nf_total_carbohydrate': 1.03,
  'nf_dietary_fiber': 0.35,
  'nf_sugars': 0.05,
  'nf_protein': 0.15},
 {'user_input': '1 teaspoon white miso paste',
  'food_name': 'miso paste',
  'serving_qty': 1,
  'serving_unit': 'teaspoon',
  'serving_weight_grams': 5.7,
  'nf_calories': 11.28,
  'nf_total_fat': 0.34,
  'nf_saturated_fat': 0.06,
  'nf_total_carbohydrate': 1.45,
  'nf_dietary_fiber': 0.31,
  'nf_sugars': 0.35,
  'nf_protein': 0.73},
 {'user_input': '0.25 teaspoon ground black pepper',
  'food_name': 'ground black pepper',
  'serving_qty': 0.25,
  'serving_unit': 'teaspoon',
  'serving_weight_grams': 0.52,
  'nf_calories': 1.3,
  'nf_total_fat': 0.02,
  'nf_saturated_fat': 0.01,
  'nf_total_carbohydrate': 0.33,
  'nf_dietary_fiber': 0.13,
  'nf_sugars': 0,
  'nf_protein': 0.05}]

def format_nutritional_info(nutritional_info):
    formatted_info = []
    for food in nutritional_info:
        formatted_info.append(
            {
                "user_input": food["user_input"],
                "Food": food["food_name"],
                "Quantity": food["serving_qty"],
                "Unit": food["serving_unit"],
                "Calories": food["nf_calories"],
                "Total Fat": food["nf_total_fat"],
                "Saturated Fat": food["nf_saturated_fat"],
                "Total Carbohydrate": food["nf_total_carbohydrate"],
                "Fiber": food["nf_dietary_fiber"],
                "Sugars": food["nf_sugars"],
                "Protein": food["nf_protein"]
            }
        )
    return formatted_info

def non_editable_columns():
    return [
        "user_input",
        "Food",
        "Unit",
        "Calories",
        "Total Fat",
        "Saturated Fat",
        "Total Carbohydrate",
        "Fiber",
        "Sugars",
        "Protein"
    ]