nutritional_info = [{'user_input': '½ cup cooked moong dal',
  'food_name': 'moong dal',
  'food_alternatives': ['green moong dal',
   'sprouted moong salad',
   'moong dal',
   'moong bean',
   'tomato dal',
   'moong salad',
   'green moong curry',
   'chana dal',
   'moong',
   'moong beans',
   'lentil dal',
   'moong dal salad',
   'dal chawal',
   'moong sprout',
   'moong sprouts',
   'dal',
   'dal rice',
   'daleem',
   'dal roti',
   'dal curry'],
  'serving_qty': 0.5,
  'serving_unit': 'cup',
  'serving_weight_grams': 103.23,
  'nf_calories': 117.83,
  'nf_total_fat': 1.02,
  'nf_saturated_fat': 0.1,
  'nf_total_carbohydrate': 20.26,
  'nf_dietary_fiber': 7.95,
  'nf_sugars': 2.9,
  'nf_protein': 7.85},
 {'user_input': '½ cup uncooked quinoa',
  'food_name': 'uncooked quinoa',
  'food_alternatives': ['uncooked quinoa',
   'cooked quinoa',
   'red quinoa',
   'quinoa uncooked',
   'quinoa, uncooked',
   'dry quinoa',
   'quinoa',
   'cupcake',
   'quinoa pasta',
   'quinoa burger',
   'quinoa chip',
   'quinoa cookie',
   'quinoa bowl',
   'quinoa salad',
   'chocolate cupcake',
   'quinoa patty',
   'quinoa bread',
   'quinoa flour',
   'quinoa cake',
   'quinoa stirfry'],
  'serving_qty': 0.5,
  'serving_unit': 'cup',
  'serving_weight_grams': 85,
  'nf_calories': 312.8,
  'nf_total_fat': 5.16,
  'nf_saturated_fat': 0.6,
  'nf_total_carbohydrate': 54.54,
  'nf_dietary_fiber': 5.95,
  'nf_sugars': None,
  'nf_protein': 12},
 {'user_input': '1 cup small-chopped cauliflower',
  'food_name': 'cauliflower',
  'food_alternatives': ['small hard candies',
   'chopped cucumber',
   'cauliflower',
   'chopped celery',
   'chopped cilantro',
   'small hard candy',
   'chopped salad',
   'chopped walnuts',
   'small french fries',
   'small apple',
   'small salad',
   'small fries',
   'small roll',
   'celery chopped',
   'cilantro chopped',
   '1% cottage cheese',
   'juice of 1 small lemon',
   'juice from 1 small lemon',
   '1% milk',
   'juice of a small lemon'],
  'serving_qty': 1,
  'serving_unit': 'cup',
  'serving_weight_grams': 124,
  'nf_calories': 28.52,
  'nf_total_fat': 0.56,
  'nf_saturated_fat': 0.09,
  'nf_total_carbohydrate': 5.1,
  'nf_dietary_fiber': 2.85,
  'nf_sugars': 2.58,
  'nf_protein': 2.28},
 {'user_input': '½ cup green peas',
  'food_name': 'green peas',
  'food_alternatives': ['green peas',
   'canned green peas',
   'pigeon peas',
   'frozen peas',
   'sweet peas',
   'black eyed peas',
   'sugar peas',
   'sugar snap peas',
   'snap peas',
   'chick peas',
   'mushy peas',
   'snow peas',
   'black peas',
   'peas',
   'cupcake',
   'green peas masala',
   'green peas canned',
   'green tea cupcake',
   'chocolate cupcake',
   'peas sprouted'],
  'serving_qty': 0.5,
  'serving_unit': 'cup',
  'serving_weight_grams': 80,
  'nf_calories': 67.2,
  'nf_total_fat': 0.18,
  'nf_saturated_fat': 0.03,
  'nf_total_carbohydrate': 12.5,
  'nf_dietary_fiber': 4.4,
  'nf_sugars': 4.74,
  'nf_protein': 4.29},
 {'user_input': '2 teaspoons grated fresh ginger',
  'food_name': 'fresh ginger',
  'food_alternatives': ['fresh ginger',
   'grated parmesan',
   'grated cheese',
   'grated gruyere',
   'grated cheddar',
   'grated parmigiano',
   'grated swiss cheese',
   'grated cheese blend',
   'grated swiss',
   'grated parmesan cheese',
   'cheddar cheese grated',
   'grated colby jack',
   'cheddar grated',
   'grated carrots',
   'grated cheddar cheese',
   'grated carrot',
   'grated colby jack cheese',
   'cottage cheese 2%',
   '2% milk',
   'milk 2%'],
  'serving_qty': 2,
  'serving_unit': 'teaspoons',
  'serving_weight_grams': 4.56,
  'nf_calories': 3.64,
  'nf_total_fat': 0.03,
  'nf_saturated_fat': 0.01,
  'nf_total_carbohydrate': 0.81,
  'nf_dietary_fiber': 0.09,
  'nf_sugars': 0.08,
  'nf_protein': 0.08},
 {'user_input': '1 teaspoon ground coriander',
  'food_name': 'ground coriander',
  'food_alternatives': ['ground coriander',
   'fresh coriander',
   'dried coriander',
   'raw coriander',
   'coriander',
   'ground beef',
   'fresh coriander leaves',
   'dried coriander leaf',
   'coriander leaves',
   'coriander seed',
   '1% cottage cheese',
   '16% fat cream cheese',
   '100% apple juice',
   'coriander seeds',
   'coriander leaf',
   'cottage cheese 1%',
   '100% juice apple',
   '1% latte',
   '1% chocolate milk',
   '1% milk'],
  'serving_qty': 1,
  'serving_unit': 'teaspoon',
  'serving_weight_grams': 1.73,
  'nf_calories': 5.17,
  'nf_total_fat': 0.31,
  'nf_saturated_fat': 0.02,
  'nf_total_carbohydrate': 0.95,
  'nf_dietary_fiber': 0.73,
  'nf_sugars': None,
  'nf_protein': 0.21},
 {'user_input': '½ teaspoon ground cumin',
  'food_name': 'ground cumin',
  'food_alternatives': ['ground cumin',
   'lean ground beef',
   'oil cumin',
   'ground beef',
   'ground turkey',
   'ground chicken',
   'ground pork',
   'ground cinnamon',
   'ground ginger',
   'cumin',
   'spicy cumin pork',
   'chinese cumin chicken',
   'cumin oil',
   'cumins',
   'cumin seeds',
   'cumin seed',
   'cumin chicken chinese',
   'trinidadian spicy cumin pork',
   'chinese cumin chicken thigh',
   'cumin chicken thigh chinese'],
  'serving_qty': 0.5,
  'serving_unit': 'teaspoon',
  'serving_weight_grams': 1.03,
  'nf_calories': 3.84,
  'nf_total_fat': 0.23,
  'nf_saturated_fat': 0.02,
  'nf_total_carbohydrate': 0.45,
  'nf_dietary_fiber': 0.11,
  'nf_sugars': 0.02,
  'nf_protein': 0.18},
 {'user_input': '½ teaspoon ground turmeric',
  'food_name': 'ground turmeric',
  'food_alternatives': ['ground turmeric',
   'lean ground beef',
   '93% ground turkey',
   'ground turkey',
   'ground cumin',
   'ground ginger',
   'turmeric',
   'ground beef',
   'ground pork',
   'ground lamb',
   'ground chicken',
   'ground cinnamon',
   'ginger ground',
   'ground beef 93',
   'ground chuck',
   'ground coriander',
   'turmeric tonic',
   'dr oz turmeric tonic',
   'ground black pepper',
   'vietnamese turmeric fish with noodles'],
  'serving_qty': 0.5,
  'serving_unit': 'teaspoon',
  'serving_weight_grams': 1.53,
  'nf_calories': 4.78,
  'nf_total_fat': 0.05,
  'nf_saturated_fat': 0.03,
  'nf_total_carbohydrate': 1.03,
  'nf_dietary_fiber': 0.35,
  'nf_sugars': 0.05,
  'nf_protein': 0.15},
 {'user_input': '1 teaspoon white miso paste',
  'food_name': 'miso paste',
  'food_alternatives': ['miso paste',
   'tomato paste',
   'organic miso soup',
   'low sodium miso',
   'miso sauce',
   'cottage cheese 1%',
   '1% chocolate milk',
   'miso soups',
   'miso ramen soup',
   'miso soup',
   'miso ramen',
   '1% cottage cheese',
   'miso low sodium',
   '16% fat cream cheese',
   'miso dressing',
   '1% latte',
   'ginger miso dressing',
   'miso',
   '1% milk',
   'miso ginger dressing'],
  'serving_qty': 1,
  'serving_unit': 'teaspoon',
  'serving_weight_grams': 5.7,
  'nf_calories': 11.28,
  'nf_total_fat': 0.34,
  'nf_saturated_fat': 0.06,
  'nf_total_carbohydrate': 1.45,
  'nf_dietary_fiber': 0.31,
  'nf_sugars': 0.35,
  'nf_protein': 0.73},
 {'user_input': '¼ teaspoon ground black pepper',
  'food_name': 'ground black pepper',
  'food_alternatives': ['ground black pepper',
   'sea salt and black pepper',
   'salt and freshly ground black pepper',
   'ground red pepper',
   'sea salt and freshly ground black pepper',
   'ground pepper',
   'black pepper',
   'ground red chili pepper',
   'salt and freshly ground pepper',
   'ground beef',
   'ground beef stuffed pepper',
   'ground beef stuffed green pepper',
   'sea salt and freshly ground pepper',
   'tuna black pepper crusted',
   'black pepper tuna',
   'black pepper chicken',
   'chinese black pepper chicken',
   'black pepper turkey',
   'black pepper turkey breast',
   'black pepper crusted tuna'],
  'serving_qty': 0.25,
  'serving_unit': 'teaspoon',
  'serving_weight_grams': 0.52,
  'nf_calories': 1.3,
  'nf_total_fat': 0.02,
  'nf_saturated_fat': 0.01,
  'nf_total_carbohydrate': 0.33,
  'nf_dietary_fiber': 0.13,
  'nf_sugars': 0,
  'nf_protein': 0.05}]

def format_nutritional_info(nutritional_info):
    print("@@@@@@@@@")
    print("format_nutritional_info")
    formatted_info = []
    for food in nutritional_info:
        
        food["food_alternatives"].insert(0, "Select")
        print(food["food_alternatives"])
        print(food["food_name"])
        formatted_info.append(
            {
                "user_input": food["user_input"],
                "Food": food["food_name"],
                "Food_alternatives": food["food_alternatives"],
                "Quantity": food["serving_qty"],
                "Unit": food["serving_unit"],
                "Calories": food["nf_calories"],
                "Total Fat": food["nf_total_fat"],
                "Saturated Fat": food["nf_saturated_fat"],
                "Total Carbohydrate": food["nf_total_carbohydrate"],
                "Fiber": food["nf_dietary_fiber"],
                "Sugars": food["nf_sugars"],
                "Protein": food["nf_protein"]
            }
        )
    return formatted_info

def non_editable_columns():
    return [
        "user_input",
        "Food",
        "Unit",
        "Calories",
        "Total Fat",
        "Saturated Fat",
        "Total Carbohydrate",
        "Fiber",
        "Sugars",
        "Protein"
    ]